#pragma once

#define  TRACEPOS TRACE(L"%s<%d>\n", __FUNCTION__, __LINE__);
//#define DBG(x...) {TRACE(L"\e[033;34m%s<%d> \e[0m",__FUNCTION__,__LINE__); TRACE(x);}
//#define FATAL(x...) {TRACE(L"\e[033;31m%s<%d> \e[0m",__FUNCTION__,__LINE__); TRACE(x);}

#define GRAPH_Y_AXIS_LENGTH			(150)
#define GRAPH_X_AXIS_LENGTH			(500)

#define GRAPH_Y_COORD				(150)
#define GRAPH_X_COORD				(0)

#define MAIN_DLG_WIDTH 1000
#define MAIN_DLG_HEIGHT 650

#define NUMBER_OF_MENU_TAB		(6) //system, status, network, services, firewall, logs
#define NUMBER_OF_SYSTEM_TAB	(4)
#define NUMBER_OF_STATUS_TAB	(9)
#define NUMBER_OF_NETWORK_TAB	(8)
#define NUMBER_OF_SERVICES_TAB	(6)
#define NUMBER_OF_FIREWALL_TAB	(5)
#define NUMBER_OF_LOGS_TAB		(11)


#define TAB_MENU_OFFSET_LEFT	(10)
#define TAB_MENU_OFFSET_RIGHT	(-15)
#define TAB_MENU_OFFSET_TOP		( 80)
#define TAB_MENU_OFFSET_BOTTOM	(-30)

#define SUB_TAB_OFFSET_LEFT		(0)
#define SUB_TAB_OFFSET_RIGHT	(MAIN_DLG_WIDTH - SUB_TAB_OFFSET_LEFT )
#define SUB_TAB_OFFSET_TOP		(20)
#define SUB_TAB_OFFSET_BOTTOM	(MAIN_DLG_HEIGHT - SUB_TAB_OFFSET_TOP )



enum TabTopMenu_t{
	TAB_MENU_LOGIN = -3,
	TAB_MENU_DEFAULT = -2,//System::Home dlg
	TAB_MENU_ONSIZE = -1, //resize child dlg
	TAB_MENU_SYSTEM = 0,
	TAB_MENU_STATUS,
	TAB_MENU_NETWORK,
	TAB_MENU_SERVICES,
	TAB_MENU_FIREWALL,
	TAB_MENU_LOGS,
};

enum TabSystem_t{
	TAB_SYSTEM_HOME = 0,
	TAB_SYSTEM_BACKUP,
	TAB_SYSTEM_SYSINFORMATION,
	TAB_SYSTEM_SHUTDOWN,
};


enum TabStatus_t{
	TAB_STATUS_SYSTEM = 0,
	TAB_STATUS_SERVICES,
	TAB_STATUS_NETWORK_EXTERNAL,
	TAB_STATUS_NETWORK_INTERNAL,
	TAB_STATUS_NETWORK_OTHER,
	TAB_STATUS_IPSEC_VPN,
	TAB_STATUS_SSL_VPN,
	TAB_STATUS_CONNECTION,
	TAB_STATUS_NETTRAFFIC,
};

enum TabNetwork_t{
	TAB_NETWORK_WEBPROXY = 0,
	TAB_NETWORK_URL_FILTER,
	TAB_NETWORK_DHCP_SERVER,
	TAB_NETWORK_CONNECTION_SCHEDULER,
	TAB_NETWORK_EDIT_HOSTS,
	TAB_NETWORK_DNS_SERVER,
	TAB_NETWORK_DNS_FORWARDING,
	TAB_NETWORK_ROUTING,
};

enum TabServices_t{
	TAB_SERVICES_IPSEC_VPN = 0,
	TAB_SERVICES_SSL_VPN,
	TAB_SERVICES_DYNAMIC_DNS,
	TAB_SERVICES_TIME_SERVER,
	TAB_SERVICES_QOS,
	TAB_SERVICES_IDS,
};

enum TabFirewall_t{
	TAB_FIREWALL_RULES = 0,
	TAB_FIREWALL_GROUPS,
	TAB_FIREWALL_OPTIONS,
	TAB_FIREWALL_P2P,
	TAB_FIREWALL_GEOIP,
};


enum TabLogs_t{
	TAB_LOGS_SUMMARY = 0,
	TAB_LOGS_SETTINGS,
	TAB_LOGS_PROXY_LOGS,
	TAB_LOGS_PROXY_REPORTS,
	TAB_LOGS_FIREWALL_LOGS,
	TAB_LOGS_FW_LOGGRAPHS_IP,
	TAB_LOGS_FW_LOGGRAPHS_PORT,
	TAB_LOGS_FW_LOGGRAPHS_COUNTRY,
	TAB_LOGS_IDS,
	TAB_LOGS_URL_FILTER,
	TAB_LOGS_SYSTEM,
};


#define WAITING_PICTURE "res/waiting.gif"

// System > Home
#define CQUICKLIST_WIDTH_DEFAULT (180)



