/* soapServer.cpp
   Generated by gSOAP 2.8.23 from ctSoap.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.23 2015-10-29 07:26:57 GMT")


extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:putData"))
		return soap_serve_ns__putData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getData"))
		return soap_serve_ns__getData(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getImage"))
		return soap_serve_ns__getImage(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:login"))
		return soap_serve_ns__login(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getRuntimeInfo"))
		return soap_serve_ns__getRuntimeInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getSysHomeInterface"))
		return soap_serve_ns__getSysHomeInterface(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SysBackupHandle"))
		return soap_serve_ns__SysBackupHandle(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getSysSysInfo"))
		return soap_serve_ns__getSysSysInfo(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SysShutdownHandle"))
		return soap_serve_ns__SysShutdownHandle(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getStatusSystemGraph"))
		return soap_serve_ns__getStatusSystemGraph(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getStatusNetworkExternal"))
		return soap_serve_ns__getStatusNetworkExternal(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getStatusNetworkInternal"))
		return soap_serve_ns__getStatusNetworkInternal(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getStatusNetworkOther"))
		return soap_serve_ns__getStatusNetworkOther(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getStatusServices"))
		return soap_serve_ns__getStatusServices(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:getStatusConnection"))
		return soap_serve_ns__getStatusConnection(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__putData(struct soap *soap)
{	struct ns__putData soap_tmp_ns__putData;
	struct ns__putDataResponse soap_tmp_ns__putDataResponse;
	arrayOfName soap_tmp_arrayOfName;
	soap_default_ns__putDataResponse(soap, &soap_tmp_ns__putDataResponse);
	soap_tmp_arrayOfName.soap_default(soap);
	soap_tmp_ns__putDataResponse.names = &soap_tmp_arrayOfName;
	soap_default_ns__putData(soap, &soap_tmp_ns__putData);
	if (!soap_get_ns__putData(soap, &soap_tmp_ns__putData, "ns:putData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__putData(soap, soap_tmp_ns__putData.nameList, soap_tmp_ns__putData.data, soap_tmp_ns__putDataResponse.names);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__putDataResponse(soap, &soap_tmp_ns__putDataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__putDataResponse(soap, &soap_tmp_ns__putDataResponse, "ns:putDataResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__putDataResponse(soap, &soap_tmp_ns__putDataResponse, "ns:putDataResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getData(struct soap *soap)
{	struct ns__getData soap_tmp_ns__getData;
	struct ns__getDataResponse soap_tmp_ns__getDataResponse;
	arrayOfData soap_tmp_arrayOfData;
	soap_default_ns__getDataResponse(soap, &soap_tmp_ns__getDataResponse);
	soap_tmp_arrayOfData.soap_default(soap);
	soap_tmp_ns__getDataResponse.data = &soap_tmp_arrayOfData;
	soap_default_ns__getData(soap, &soap_tmp_ns__getData);
	if (!soap_get_ns__getData(soap, &soap_tmp_ns__getData, "ns:getData", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getData(soap, soap_tmp_ns__getData.names, soap_tmp_ns__getDataResponse.data);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__getDataResponse(soap, &soap_tmp_ns__getDataResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getDataResponse(soap, &soap_tmp_ns__getDataResponse, "ns:getDataResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getDataResponse(soap, &soap_tmp_ns__getDataResponse, "ns:getDataResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getImage(struct soap *soap)
{	struct ns__getImage soap_tmp_ns__getImage;
	struct ns__getImageResponse soap_tmp_ns__getImageResponse;
	soap_default_ns__getImageResponse(soap, &soap_tmp_ns__getImageResponse);
	soap_default_ns__getImage(soap, &soap_tmp_ns__getImage);
	if (!soap_get_ns__getImage(soap, &soap_tmp_ns__getImage, "ns:getImage", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getImage(soap, soap_tmp_ns__getImage.name, soap_tmp_ns__getImageResponse.image);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__getImageResponse(soap, &soap_tmp_ns__getImageResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getImageResponse(soap, &soap_tmp_ns__getImageResponse, "ns:getImageResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getImageResponse(soap, &soap_tmp_ns__getImageResponse, "ns:getImageResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__login(struct soap *soap)
{	struct ns__login soap_tmp_ns__login;
	struct ns__loginResponse soap_tmp_ns__loginResponse;
	bool soap_tmp_bool;
	soap_default_ns__loginResponse(soap, &soap_tmp_ns__loginResponse);
	soap_default_bool(soap, &soap_tmp_bool);
	soap_tmp_ns__loginResponse.ret = &soap_tmp_bool;
	soap_default_ns__login(soap, &soap_tmp_ns__login);
	if (!soap_get_ns__login(soap, &soap_tmp_ns__login, "ns:login", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__login(soap, soap_tmp_ns__login.username, soap_tmp_ns__login.passwd, soap_tmp_ns__loginResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__loginResponse(soap, &soap_tmp_ns__loginResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__loginResponse(soap, &soap_tmp_ns__loginResponse, "ns:loginResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__loginResponse(soap, &soap_tmp_ns__loginResponse, "ns:loginResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getRuntimeInfo(struct soap *soap)
{	struct ns__getRuntimeInfo soap_tmp_ns__getRuntimeInfo;
	struct ns__getRuntimeInfoResponse soap_tmp_ns__getRuntimeInfoResponse;
	RuntimeInfo_t soap_tmp_RuntimeInfo_t;
	soap_default_ns__getRuntimeInfoResponse(soap, &soap_tmp_ns__getRuntimeInfoResponse);
	soap_tmp_RuntimeInfo_t.soap_default(soap);
	soap_tmp_ns__getRuntimeInfoResponse.ret = &soap_tmp_RuntimeInfo_t;
	soap_default_ns__getRuntimeInfo(soap, &soap_tmp_ns__getRuntimeInfo);
	if (!soap_get_ns__getRuntimeInfo(soap, &soap_tmp_ns__getRuntimeInfo, "ns:getRuntimeInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getRuntimeInfo(soap, soap_tmp_ns__getRuntimeInfo._param_9, soap_tmp_ns__getRuntimeInfoResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__getRuntimeInfoResponse(soap, &soap_tmp_ns__getRuntimeInfoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getRuntimeInfoResponse(soap, &soap_tmp_ns__getRuntimeInfoResponse, "ns:getRuntimeInfoResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getRuntimeInfoResponse(soap, &soap_tmp_ns__getRuntimeInfoResponse, "ns:getRuntimeInfoResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getSysHomeInterface(struct soap *soap)
{	struct ns__getSysHomeInterface soap_tmp_ns__getSysHomeInterface;
	struct ns__getSysHomeInterfaceResponse soap_tmp_ns__getSysHomeInterfaceResponse;
	NetInterface_t soap_tmp_NetInterface_t;
	soap_default_ns__getSysHomeInterfaceResponse(soap, &soap_tmp_ns__getSysHomeInterfaceResponse);
	soap_tmp_NetInterface_t.soap_default(soap);
	soap_tmp_ns__getSysHomeInterfaceResponse.ret = &soap_tmp_NetInterface_t;
	soap_default_ns__getSysHomeInterface(soap, &soap_tmp_ns__getSysHomeInterface);
	if (!soap_get_ns__getSysHomeInterface(soap, &soap_tmp_ns__getSysHomeInterface, "ns:getSysHomeInterface", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getSysHomeInterface(soap, soap_tmp_ns__getSysHomeInterface._param_10, soap_tmp_ns__getSysHomeInterfaceResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__getSysHomeInterfaceResponse(soap, &soap_tmp_ns__getSysHomeInterfaceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getSysHomeInterfaceResponse(soap, &soap_tmp_ns__getSysHomeInterfaceResponse, "ns:getSysHomeInterfaceResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getSysHomeInterfaceResponse(soap, &soap_tmp_ns__getSysHomeInterfaceResponse, "ns:getSysHomeInterfaceResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SysBackupHandle(struct soap *soap)
{	struct ns__SysBackupHandle soap_tmp_ns__SysBackupHandle;
	struct ns__SysBackupHandleResponse soap_tmp_ns__SysBackupHandleResponse;
	SysBackupRet_t soap_tmp_SysBackupRet_t;
	soap_default_ns__SysBackupHandleResponse(soap, &soap_tmp_ns__SysBackupHandleResponse);
	soap_tmp_SysBackupRet_t.soap_default(soap);
	soap_tmp_ns__SysBackupHandleResponse.ret = &soap_tmp_SysBackupRet_t;
	soap_default_ns__SysBackupHandle(soap, &soap_tmp_ns__SysBackupHandle);
	if (!soap_get_ns__SysBackupHandle(soap, &soap_tmp_ns__SysBackupHandle, "ns:SysBackupHandle", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SysBackupHandle(soap, soap_tmp_ns__SysBackupHandle.in, soap_tmp_ns__SysBackupHandle.path, soap_tmp_ns__SysBackupHandleResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__SysBackupHandleResponse(soap, &soap_tmp_ns__SysBackupHandleResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__SysBackupHandleResponse(soap, &soap_tmp_ns__SysBackupHandleResponse, "ns:SysBackupHandleResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__SysBackupHandleResponse(soap, &soap_tmp_ns__SysBackupHandleResponse, "ns:SysBackupHandleResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getSysSysInfo(struct soap *soap)
{	struct ns__getSysSysInfo soap_tmp_ns__getSysSysInfo;
	struct ns__getSysSysInfoResponse soap_tmp_ns__getSysSysInfoResponse;
	SysInfo_t soap_tmp_SysInfo_t;
	soap_default_ns__getSysSysInfoResponse(soap, &soap_tmp_ns__getSysSysInfoResponse);
	soap_tmp_SysInfo_t.soap_default(soap);
	soap_tmp_ns__getSysSysInfoResponse.ret = &soap_tmp_SysInfo_t;
	soap_default_ns__getSysSysInfo(soap, &soap_tmp_ns__getSysSysInfo);
	if (!soap_get_ns__getSysSysInfo(soap, &soap_tmp_ns__getSysSysInfo, "ns:getSysSysInfo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getSysSysInfo(soap, soap_tmp_ns__getSysSysInfo._param_11, soap_tmp_ns__getSysSysInfoResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__getSysSysInfoResponse(soap, &soap_tmp_ns__getSysSysInfoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getSysSysInfoResponse(soap, &soap_tmp_ns__getSysSysInfoResponse, "ns:getSysSysInfoResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getSysSysInfoResponse(soap, &soap_tmp_ns__getSysSysInfoResponse, "ns:getSysSysInfoResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SysShutdownHandle(struct soap *soap)
{	struct ns__SysShutdownHandle soap_tmp_ns__SysShutdownHandle;
	struct ns__noResponse out;
	soap_default_ns__noResponse(soap, &out);
	soap_default_ns__SysShutdownHandle(soap, &soap_tmp_ns__SysShutdownHandle);
	if (!soap_get_ns__SysShutdownHandle(soap, &soap_tmp_ns__SysShutdownHandle, "ns:SysShutdownHandle", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SysShutdownHandle(soap, soap_tmp_ns__SysShutdownHandle.in, &out);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__noResponse(soap, &out);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__noResponse(soap, &out, "ns:noResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__noResponse(soap, &out, "ns:noResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getStatusSystemGraph(struct soap *soap)
{	struct ns__getStatusSystemGraph soap_tmp_ns__getStatusSystemGraph;
	struct ns__getStatusSystemGraphResponse soap_tmp_ns__getStatusSystemGraphResponse;
	SystemData_t soap_tmp_SystemData_t;
	soap_default_ns__getStatusSystemGraphResponse(soap, &soap_tmp_ns__getStatusSystemGraphResponse);
	soap_tmp_SystemData_t.soap_default(soap);
	soap_tmp_ns__getStatusSystemGraphResponse.ret = &soap_tmp_SystemData_t;
	soap_default_ns__getStatusSystemGraph(soap, &soap_tmp_ns__getStatusSystemGraph);
	if (!soap_get_ns__getStatusSystemGraph(soap, &soap_tmp_ns__getStatusSystemGraph, "ns:getStatusSystemGraph", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getStatusSystemGraph(soap, soap_tmp_ns__getStatusSystemGraph.mode, soap_tmp_ns__getStatusSystemGraphResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__getStatusSystemGraphResponse(soap, &soap_tmp_ns__getStatusSystemGraphResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getStatusSystemGraphResponse(soap, &soap_tmp_ns__getStatusSystemGraphResponse, "ns:getStatusSystemGraphResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getStatusSystemGraphResponse(soap, &soap_tmp_ns__getStatusSystemGraphResponse, "ns:getStatusSystemGraphResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getStatusNetworkExternal(struct soap *soap)
{	struct ns__getStatusNetworkExternal soap_tmp_ns__getStatusNetworkExternal;
	struct ns__getStatusNetworkExternalResponse soap_tmp_ns__getStatusNetworkExternalResponse;
	NetworkData_t soap_tmp_NetworkData_t;
	soap_default_ns__getStatusNetworkExternalResponse(soap, &soap_tmp_ns__getStatusNetworkExternalResponse);
	soap_tmp_NetworkData_t.soap_default(soap);
	soap_tmp_ns__getStatusNetworkExternalResponse.ret = &soap_tmp_NetworkData_t;
	soap_default_ns__getStatusNetworkExternal(soap, &soap_tmp_ns__getStatusNetworkExternal);
	if (!soap_get_ns__getStatusNetworkExternal(soap, &soap_tmp_ns__getStatusNetworkExternal, "ns:getStatusNetworkExternal", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getStatusNetworkExternal(soap, soap_tmp_ns__getStatusNetworkExternal.mode, soap_tmp_ns__getStatusNetworkExternalResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__getStatusNetworkExternalResponse(soap, &soap_tmp_ns__getStatusNetworkExternalResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getStatusNetworkExternalResponse(soap, &soap_tmp_ns__getStatusNetworkExternalResponse, "ns:getStatusNetworkExternalResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getStatusNetworkExternalResponse(soap, &soap_tmp_ns__getStatusNetworkExternalResponse, "ns:getStatusNetworkExternalResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getStatusNetworkInternal(struct soap *soap)
{	struct ns__getStatusNetworkInternal soap_tmp_ns__getStatusNetworkInternal;
	struct ns__getStatusNetworkInternalResponse soap_tmp_ns__getStatusNetworkInternalResponse;
	NetworkData_t soap_tmp_NetworkData_t;
	soap_default_ns__getStatusNetworkInternalResponse(soap, &soap_tmp_ns__getStatusNetworkInternalResponse);
	soap_tmp_NetworkData_t.soap_default(soap);
	soap_tmp_ns__getStatusNetworkInternalResponse.ret = &soap_tmp_NetworkData_t;
	soap_default_ns__getStatusNetworkInternal(soap, &soap_tmp_ns__getStatusNetworkInternal);
	if (!soap_get_ns__getStatusNetworkInternal(soap, &soap_tmp_ns__getStatusNetworkInternal, "ns:getStatusNetworkInternal", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getStatusNetworkInternal(soap, soap_tmp_ns__getStatusNetworkInternal.mode, soap_tmp_ns__getStatusNetworkInternalResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__getStatusNetworkInternalResponse(soap, &soap_tmp_ns__getStatusNetworkInternalResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getStatusNetworkInternalResponse(soap, &soap_tmp_ns__getStatusNetworkInternalResponse, "ns:getStatusNetworkInternalResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getStatusNetworkInternalResponse(soap, &soap_tmp_ns__getStatusNetworkInternalResponse, "ns:getStatusNetworkInternalResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getStatusNetworkOther(struct soap *soap)
{	struct ns__getStatusNetworkOther soap_tmp_ns__getStatusNetworkOther;
	struct ns__getStatusNetworkOtherResponse soap_tmp_ns__getStatusNetworkOtherResponse;
	NetworkData_t soap_tmp_NetworkData_t;
	soap_default_ns__getStatusNetworkOtherResponse(soap, &soap_tmp_ns__getStatusNetworkOtherResponse);
	soap_tmp_NetworkData_t.soap_default(soap);
	soap_tmp_ns__getStatusNetworkOtherResponse.ret = &soap_tmp_NetworkData_t;
	soap_default_ns__getStatusNetworkOther(soap, &soap_tmp_ns__getStatusNetworkOther);
	if (!soap_get_ns__getStatusNetworkOther(soap, &soap_tmp_ns__getStatusNetworkOther, "ns:getStatusNetworkOther", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getStatusNetworkOther(soap, soap_tmp_ns__getStatusNetworkOther.mode, soap_tmp_ns__getStatusNetworkOtherResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__getStatusNetworkOtherResponse(soap, &soap_tmp_ns__getStatusNetworkOtherResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getStatusNetworkOtherResponse(soap, &soap_tmp_ns__getStatusNetworkOtherResponse, "ns:getStatusNetworkOtherResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getStatusNetworkOtherResponse(soap, &soap_tmp_ns__getStatusNetworkOtherResponse, "ns:getStatusNetworkOtherResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getStatusServices(struct soap *soap)
{	struct ns__getStatusServices soap_tmp_ns__getStatusServices;
	struct ns__getStatusServicesResponse soap_tmp_ns__getStatusServicesResponse;
	std::vector<StatusServices_t > soap_tmp_StatusServicesList_t;
	soap_default_ns__getStatusServicesResponse(soap, &soap_tmp_ns__getStatusServicesResponse);
	soap_default_StatusServicesList_t(soap, &soap_tmp_StatusServicesList_t);
	soap_tmp_ns__getStatusServicesResponse.ret = &soap_tmp_StatusServicesList_t;
	soap_default_ns__getStatusServices(soap, &soap_tmp_ns__getStatusServices);
	if (!soap_get_ns__getStatusServices(soap, &soap_tmp_ns__getStatusServices, "ns:getStatusServices", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getStatusServices(soap, soap_tmp_ns__getStatusServices._param_12, soap_tmp_ns__getStatusServicesResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__getStatusServicesResponse(soap, &soap_tmp_ns__getStatusServicesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getStatusServicesResponse(soap, &soap_tmp_ns__getStatusServicesResponse, "ns:getStatusServicesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getStatusServicesResponse(soap, &soap_tmp_ns__getStatusServicesResponse, "ns:getStatusServicesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getStatusConnection(struct soap *soap)
{	struct ns__getStatusConnection soap_tmp_ns__getStatusConnection;
	struct ns__getStatusConnectionResponse soap_tmp_ns__getStatusConnectionResponse;
	std::vector<ConnTrack_t > soap_tmp_StatusConnList_t;
	soap_default_ns__getStatusConnectionResponse(soap, &soap_tmp_ns__getStatusConnectionResponse);
	soap_default_StatusConnList_t(soap, &soap_tmp_StatusConnList_t);
	soap_tmp_ns__getStatusConnectionResponse.ret = &soap_tmp_StatusConnList_t;
	soap_default_ns__getStatusConnection(soap, &soap_tmp_ns__getStatusConnection);
	if (!soap_get_ns__getStatusConnection(soap, &soap_tmp_ns__getStatusConnection, "ns:getStatusConnection", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__getStatusConnection(soap, soap_tmp_ns__getStatusConnection._param_13, soap_tmp_ns__getStatusConnectionResponse.ret);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = "";
	soap_serializeheader(soap);
	soap_serialize_ns__getStatusConnectionResponse(soap, &soap_tmp_ns__getStatusConnectionResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__getStatusConnectionResponse(soap, &soap_tmp_ns__getStatusConnectionResponse, "ns:getStatusConnectionResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__getStatusConnectionResponse(soap, &soap_tmp_ns__getStatusConnectionResponse, "ns:getStatusConnectionResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
