/* soapStub.h
   Generated by gSOAP 2.8.23 from dime.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20823
# error "GSOAP VERSION 20823 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns__Data
#define SOAP_TYPE_ns__Data (7)
/* Base64 schema type: */
class SOAP_CMAC ns__Data
{
public:
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
	ns__Data();	/* transient */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 7; } /* = unique type id SOAP_TYPE_ns__Data */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	virtual ~ns__Data() { }
};
#endif

#ifndef SOAP_TYPE_arrayOfData
#define SOAP_TYPE_arrayOfData (15)
/* SOAP encoded array of ns:Data schema type: */
class SOAP_CMAC arrayOfData
{
public:
	ns__Data *__ptr;
	int __size;
	arrayOfData();	/* transient */
	arrayOfData(struct soap *_param_1, int _param_2);	/* transient */
	virtual ~arrayOfData();	/* transient */
	int size();	/* transient */
	void resize(int _param_3);	/* transient */
	ns__Data &operator[](int _param_4) const;	/* transient */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 15; } /* = unique type id SOAP_TYPE_arrayOfData */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
};
#endif

#ifndef SOAP_TYPE_arrayOfName
#define SOAP_TYPE_arrayOfName (26)
/* SOAP encoded array of xsd:string schema type: */
class SOAP_CMAC arrayOfName
{
public:
	char **__ptr;
	int __size;
	arrayOfName();	/* transient */
	arrayOfName(struct soap *_param_5, int _param_6);	/* transient */
	virtual ~arrayOfName();	/* transient */
	int size();	/* transient */
	void resize(int _param_7);	/* transient */
	char *&operator[](int _param_8) const;	/* transient */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 26; } /* = unique type id SOAP_TYPE_arrayOfName */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
};
#endif

#ifndef SOAP_TYPE_ns__putDataResponse
#define SOAP_TYPE_ns__putDataResponse (38)
/* ns:putDataResponse */
struct ns__putDataResponse
{
public:
	arrayOfName *names;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfstring */
public:
	int soap_type() const { return 38; } /* = unique type id SOAP_TYPE_ns__putDataResponse */
};
#endif

#ifndef SOAP_TYPE_ns__putData
#define SOAP_TYPE_ns__putData (39)
/* ns:putData */
struct ns__putData
{
public:
	arrayOfData *data;	/* optional element of type ArrayOfData */
public:
	int soap_type() const { return 39; } /* = unique type id SOAP_TYPE_ns__putData */
};
#endif

#ifndef SOAP_TYPE_ns__getDataResponse
#define SOAP_TYPE_ns__getDataResponse (41)
/* ns:getDataResponse */
struct ns__getDataResponse
{
public:
	arrayOfData *data;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfData */
public:
	int soap_type() const { return 41; } /* = unique type id SOAP_TYPE_ns__getDataResponse */
};
#endif

#ifndef SOAP_TYPE_ns__getData
#define SOAP_TYPE_ns__getData (42)
/* ns:getData */
struct ns__getData
{
public:
	arrayOfName *names;	/* optional element of type ArrayOfstring */
public:
	int soap_type() const { return 42; } /* = unique type id SOAP_TYPE_ns__getData */
};
#endif

#ifndef SOAP_TYPE_ns__getImageResponse
#define SOAP_TYPE_ns__getImageResponse (44)
/* ns:getImageResponse */
struct ns__getImageResponse
{
public:
	ns__Data image;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns:Data */
public:
	int soap_type() const { return 44; } /* = unique type id SOAP_TYPE_ns__getImageResponse */
};
#endif

#ifndef SOAP_TYPE_ns__getImage
#define SOAP_TYPE_ns__getImage (45)
/* ns:getImage */
struct ns__getImage
{
public:
	char *name;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 45; } /* = unique type id SOAP_TYPE_ns__getImage */
};
#endif

#ifndef SOAP_TYPE_ns__addResponse
#define SOAP_TYPE_ns__addResponse (49)
/* ns:addResponse */
struct ns__addResponse
{
public:
	float *ret;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:float */
public:
	int soap_type() const { return 49; } /* = unique type id SOAP_TYPE_ns__addResponse */
};
#endif

#ifndef SOAP_TYPE_ns__add
#define SOAP_TYPE_ns__add (50)
/* ns:add */
struct ns__add
{
public:
	float a;	/* required element of type xsd:float */
	float b;	/* required element of type xsd:float */
public:
	int soap_type() const { return 50; } /* = unique type id SOAP_TYPE_ns__add */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (51)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 51; } /* = unique type id SOAP_TYPE_SOAP_ENV__Header */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (52)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 52; } /* = unique type id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (54)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 54; } /* = unique type id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (56)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 56; } /* = unique type id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (57)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 57; } /* = unique type id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns__putData(struct soap*, arrayOfData *data, arrayOfName *names);

SOAP_FMAC5 int SOAP_FMAC6 ns__getData(struct soap*, arrayOfName *names, arrayOfData *data);

SOAP_FMAC5 int SOAP_FMAC6 ns__getImage(struct soap*, char *name, ns__Data &image);

SOAP_FMAC5 int SOAP_FMAC6 ns__add(struct soap*, float a, float b, float *ret);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__putData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getData(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__getImage(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__add(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__putData(struct soap *soap, const char *soap_endpoint, const char *soap_action, arrayOfData *data, arrayOfName *names);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getData(struct soap *soap, const char *soap_endpoint, const char *soap_action, arrayOfName *names, arrayOfData *data);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__getImage(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *name, ns__Data &image);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__add(struct soap *soap, const char *soap_endpoint, const char *soap_action, float a, float b, float *ret);

#endif

/* End of soapStub.h */
